### ISSUE TITLE
Error in GUI Tool MAC OS - Silicon (M2)

### ISSUE THREAD

**Issue by DannMendis** [marcherschel/UpdateTool#119]
I am still getting the same error with updatetool-gui-mac-1.0.8.jar. Given my other ticket is closed, I have raised this one.

Error Log as below.
macminibeast@MacMiniBeast Downloads % java -jar updatetool-gui-mac-1.0.8.jar
Mar 03, 2024 8:44:53 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @4d5804c6'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_es2.dylib: dlopen(/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_es2.dylib, 0x0001): tried: '/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_es2.dylib' (no such file), '/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
java.lang.UnsatisfiedLinkError: /Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_es2.dylib: dlopen(/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_es2.dylib, 0x0001): tried: '/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_es2.dylib' (no such file), '/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:63)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:52)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:421)
	at java.base/java.lang.Class.forName(Class.java:412)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: /Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_sw.dylib: dlopen(/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_sw.dylib, 0x0001): tried: '/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_sw.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_sw.dylib' (no such file), '/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_sw.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
java.lang.UnsatisfiedLinkError: /Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_sw.dylib: dlopen(/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_sw.dylib, 0x0001): tried: '/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_sw.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_sw.dylib' (no such file), '/Users/macminibeast/.openjfx/cache/19.0.2.1+1/aarch64/libprism_sw.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:43)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:42)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:421)
	at java.base/java.lang.Class.forName(Class.java:412)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:253)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:268)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:280)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:1583)
macminibeast@MacMiniBeast Downloads %

**Comment by DannMendis** [comment]
@mynttt any help with this much appreciated.

**Comment by mynttt** [comment]
@DannMendis I have an M3 Mac from my work now. I might find time in the next weeks to see if it runs on there.

Else I can only recommend you to run it via a bash script. If you need help with that let me know and I can get you a template.

**Comment by DannMendis** [comment]
@mynttt waiting 1 week is ok as others will be facing same issue for sure. Thanks a lot for your consideration. Much appreciated.

**Comment by DannMendis** [comment]
LOL. I managed to get it fixed. It was Java FX in the code.

**Comment by marcherschel** [comment]
workaround in https://github.com/marcherschel/UpdateTool/issues/127
